### PR TITLE
WordPress - PLA-676 update

### PR DESCRIPTION
**Pull request by james-shorthand**
This PR is part of [PLA-676](https://linear.app/shorthand/issue/PLA-676/[publishingplugins]-update-plugins-and-publishing-providers)

- Removed deprecated V1 API code
- Remove V1 / V2 API checker
- Remove unused global variables
- Fix a bug with the code that tells a user if Shorthand is reachable and/or no stories are marked 'Ready to publish.'
- Swap the config.php / config.default.php code to prevent warnings
- Update the user agent to show the WordPress & Shorthand plugin version for PLA-676.
- General code tidy up

### **New additions**

- Added an option to disable Advanced Custom Fields running on Shorthand Post Types to prevent custom fields being hidden on our post type as an experimental feature for now.
- Updated the UserAgent code to fix a cron bug

Tested between 4.9 - 6.1 on WordPress; no errors/warnings/undesired behaviour was witnessed while testing.

(Sorry for the many commits!)

### CODE REVIEW

**Review by ckortekaas — APPROVED** [review]
Looks good to me - nice cleanup! It might be good to run the whole thing through this at some point https://github.com/WordPress/WordPress-Coding-Standards.
I marked the one SonarCloud security check as safe (unzipping files concerns about size and location of where that could happen).

**Review by zeldaleung — APPROVED** [review]
👍🏼

**Review by bradly-shorthand — APPROVED** [review]
Looks good! Everything tested works as expected!

**Comment by james-shorthand** [comment]
@ckortekaas @zeldaleung @bradly-shorthand - I've requested a re-review of this as I've added code to add an option to disable ACF and updated the code to fix the corn.

Once approved, this will be pushed out this week ASAP.

**Comment by bradly-shorthand** [comment]
Hey @james-shorthand,

**There's a typo in the settings section:**
"Disable Advanced Custom Fieldss"

**Comment by james-shorthand** [comment]
> Hey @james-shorthand,
> 
> **There's a typo in the settings section:** "Disable Advanced Custom Fieldss"

Fixed! Thanks and good spot!

**Review by bradly-shorthand — APPROVED** [review]
LGTM - No ACF showing for me on the shorthand post type when enabled

**Review by ckortekaas — APPROVED** [review]
LGTM

**Pull request merged**
